#!/usr/bin/php
<?php
declare(strict_types = 1);

require_once('./vendor/autoload.php');

use RoyBongers\CertbotTransIpDns01\Bootstrap;
use RoyBongers\CertbotTransIpDns01\Certbot\Requests\CleanupHookRequest;

(new Bootstrap(new CleanupHookRequest()));
