#!/usr/bin/php
<?php
declare(strict_types = 1);

define('APP_ROOT', __DIR__);
require_once(APP_ROOT.'/vendor/autoload.php');

use RoyBongers\CertbotTransIpDns01\Bootstrap;
use RoyBongers\CertbotTransIpDns01\Certbot\Requests\CleanupHookRequest;

(new Bootstrap(new CleanupHookRequest()));
