<?php

namespace RoyBongers\CertbotDns01\Certbot;

class ChallengeRecord
{
    /**
     * Primary domain name without any subdomains (e.g. example.co.uk).
     */
    private string $domain;

    /**
     * String containing the subdomain prefix with '_acme-challenge' e.g. "_acme-challenge.sub". Note that the right dot
     * should be trimmed.
     */
    private string $recordName;

    /**
     * The unique validation string generated by Let’s Encrypt.
     */
    private string $validation;

    /**
     * ChallengeRecord constructor.
     *
     * @param string $domain     primary domain (excluding subdomains) to validate for
     * @param string $recordName string containing the subdomain prefix with '_acme-challenge'
     * @param string $validation the unique validation string generated by Let’s Encrypt
     */
    public function __construct(string $domain, string $recordName, string $validation)
    {
        $this->domain = $domain;
        $this->recordName = $recordName;
        $this->validation = $validation;
    }

    public function getDomain(): string
    {
        return $this->domain;
    }

    /**
     * Returns the name of the DNS record that should be created excluding the domain name itself.
     * e.g. _acme-challenge.sub.
     */
    public function getRecordName(): string
    {
        return $this->recordName;
    }

    /**
     * Returns the entire record name including the domain.
     * e.g. _acme-challenge.sub.domain.com.
     */
    public function getFullRecordName(): string
    {
        return $this->recordName . '.' . $this->domain;
    }

    public function getValidation(): string
    {
        return $this->validation;
    }
}
